catblock-revamp
meower-media-co/Meower-Website pull request #61
Opened 2023-06-07 19:27 UTC by MikeDev101

* Website styling and content revamp - Made by DaCatBlock.
* Updated 404 and legal-nutshell pages - Made by MikeDEV

2023-06-07 19:29 UTC, CST1229 commented on aboutus.html
rename to about.html maybe?

2023-06-07 19:29 UTC, CST1229 commented
https://catblock-revamp.meower-website.pages.dev/

2023-06-08 06:08 UTC, JoshAtticus submitted a review, later dismissed
light mode 🤮

pls add dark mode option and also go back to the old favicon

2023-06-08 10:15 UTC, HAZARD6896 commented
> light mode 🤮
> 
> pls add dark mode option and also go back to the old favicon

… light mode is fine for the Meower website imho. 
There’s something wrong with the favicon?

2023-06-08 10:24 UTC, tnix100 commented
Looks great! I actually really like this new design. One thing though, maybe we could use Feather Icons/Lucide to match what icons we use within the client?

2023-06-08 18:59 UTC, showierdata9978 requested changes

2023-06-08 18:59 UTC, showierdata9978 commented on aboutus.html
pfps do not  scale properly when hovering over

2023-06-09 02:08 UTC, JoshAtticus commented
> > light mode 🤮
> > pls add dark mode option and also go back to the old favicon
> 
> … light mode is fine for the Meower website imho. There’s something wrong with the favicon?

no its not, and the favicon has rounded corners before

2023-06-09 02:51 UTC, JoshAtticus commented
umm actually, I made the legal nutshell page, it was just edited by the duck lord 🤓
<img width="393" alt="Screenshot 2023-06-09 at 10 50 24 am" src="https://github.com/meower-media-co/Meower-Website/assets/72828296/ccab11e8-d2cf-4b4f-a98e-b9374b4dd6ca">

2023-06-09 02:52 UTC, JoshAtticus commented
<img width="462" alt="Screenshot 2023-06-09 at 10 52 14 am" src="https://github.com/meower-media-co/Meower-Website/assets/72828296/2f5c93d7-bc9d-4ac0-a9dd-296e46903b2a">
also @HAZARD6896 did you forget to remove this while using ChatGPT to make the website 🙃

2023-06-09 03:02 UTC, tnix100 commented
> <img alt="Screenshot 2023-06-09 at 10 52 14 am" width="462" src="https://user-images.githubusercontent.com/72828296/244577607-2f5c93d7-bc9d-4ac0-a9dd-296e46903b2a.png">
> 
> also @HAZARD6896 did you forget to remove this while using ChatGPT to make the website 🙃 it's quite obvious you used it lmao

How does that prove they used ChatGPT? Just seems like good code etiquette to tell other devs how the code should be formatted.

2023-06-09 03:58 UTC, JoshAtticus commented
> https://catblock-revamp.meower-website.pages.dev

I asked ChatGPT to make a few websites and all of them had that

2023-06-09 10:35 UTC, HAZARD6896 commented
> > > light mode 🤮
> > > pls add dark mode option and also go back to the old favicon
> > 
> > 
> > … light mode is fine for the Meower website imho. There’s something wrong with the favicon?
> 
> no its not, and the favicon has rounded corners before

That's a matter of personal taste. Not everyone is Josh. Light theme matches our brand.

> <img alt="Screenshot 2023-06-09 at 10 52 14 am" width="462" src="https://user-images.githubusercontent.com/72828296/244577607-2f5c93d7-bc9d-4ac0-a9dd-296e46903b2a.png">
> also @HAZARD6896 did you forget to remove this while using ChatGPT to make the website 🙃 it's quite obvious you used it lmao

I do use ChatGPT because it can streamline my workflow. I used it for basic website structure. But I also have a certification in web and graphic design that I spent this entire schoolyear studying for. My choice of tools does not make my skills and expertise any less important. Your version wasn't even mobile-friendly, so let's focus on actual problems I might have missed in the code, not roasting me.

2023-06-09 10:37 UTC, HAZARD6896 commented on aboutus.html
Could you provide more information about that? I'm not sure what you're referring to.

2023-06-09 13:49 UTC, CST1229 commented
> no its not, and the favicon has rounded corners before

IMO there shouldn't even be anything on the favicon to round corners in; we only have a 16x16 pixel space to work with, we probably shouldn't waste it on a border or background. (For example, Meower Svelte has plain Meowy as an icon, but it could also be the Meower M).

2023-06-09 13:51 UTC, tnix100 commented
> > no its not, and the favicon has rounded corners before
> 
> IMO there shouldn't even be anything on the favicon to round corners in; we only have a 16x16 pixel space to work with (in the tab bar), we probably shouldn't waste it on a border or background. For example, Meower Svelte has plain Meowy as an icon, but it could also be the Meower M.

Agreed, Meower Svelte favicon should probably be used instead of the rounded Meowy button.

2023-06-09 14:50 UTC, HAZARD6896 commented on aboutus.html
will do

2023-06-09 15:27 UTC, HAZARD6896 commented
> > > no its not, and the favicon has rounded corners before
> > 
> > 
> > IMO there shouldn't even be anything on the favicon to round corners in; we only have a 16x16 pixel space to work with (in the tab bar), we probably shouldn't waste it on a border or background. For example, Meower Svelte has plain Meowy as an icon, but it could also be the Meower M.
> 
> Agreed, Meower Svelte favicon should probably be used instead of the rounded Meowy button.

I'm getting used to this. Took me a couple tries with some things, but yes I updated the favicon as requested. Updated the icons as requested.

2023-06-09 17:52 UTC, showierdata9978 commented on aboutus.html
![image](https://github.com/meower-media-co/Meower-Website/assets/68120127/e3f8cf0b-5274-481b-862e-c11c09197d01)

2023-06-09 17:55 UTC, HAZARD6896 commented on aboutus.html
They are supposed to expand

2023-06-09 17:59 UTC, MikeDev101 commented
Please revert changes made to the 404 image: 
![image](https://github.com/meower-media-co/Meower-Website/assets/12957745/1baaff4b-05cb-4c4e-be65-822ae80b17af)

2023-06-09 18:00 UTC, MikeDev101 commented
Also noticed that the icons haven't been updated in the legal, legal-nutshell, or 404 pages.

2023-06-09 18:02 UTC, MikeDev101 commented on aboutus.html
![image](https://github.com/meower-media-co/Meower-Website/assets/12957745/bafe39d6-5937-45ec-9962-06512326a6a2)

2023-06-09 18:03 UTC, MikeDev101 commented
Converting to draft since we still can't make up our minds on what to do with the new website.

2023-06-09 18:07 UTC, showierdata9978 commented on aboutus.html
> 

They ain't properly expanding

2023-06-09 18:32 UTC, HAZARD6896 commented
> Please revert changes made to the 404 page:
> ![image](https://user-images.githubusercontent.com/12957745/244768896-1baaff4b-05cb-4c4e-be65-822ae80b17af.png)

Not sure why the image is doing that. I’ll fix it asap. It was like that previously on mobile, and I was trying to fix. The icons should all be updated with the latest link.

2023-06-09 20:30 UTC, HAZARD6896 commented on aboutus.html
I have no idea why. They should expand properly. It could be a problem with your operating system or browser, as not every browser is the same. Don't think it will affect anything either way.

2023-06-09 20:31 UTC, MikeDev101 commented
Re-opening for merging.
![image](https://github.com/meower-media-co/Meower-Website/assets/12957745/a81d5bad-045c-46f7-bc0d-fd0b112774bc)

2023-06-09 20:35 UTC, showierdata9978 commented
They are expanding, but they shift by a few pixels when the animation ends

2023-06-09 20:37 UTC, MikeDev101 commented
> They are expanding, but they shift by a few pixels when the animation ends

Not a big enough issue IMHO. It still scales.

2023-06-09 20:39 UTC, HAZARD6896 commented
> They are expanding, but they shift by a few pixels when the animation ends

That's a CSS thing. I'm not sure why I can't replicate it. Like I said, different browsers handle animations differently. Technically, the images shouldn't expand at all because that makes it look like a button, but I thought it was a nice touch.

2023-06-09 20:46 UTC, showierdata9978 commented
Firefox btw

2023-06-10 05:41 UTC, JoshAtticus commented
@HAZARD6896 please respond to my discord message

2023-06-10 15:08 UTC, Bloctans commented
*chatGPT

2023-06-10 15:08 UTC, Bloctans approved these changes
uh sure

2023-06-10 17:52 UTC, silvxrcat approved these changes

2023-06-10 18:03 UTC, silvxrcat commented
this is looking good, please style /discord tho lol :3

2023-06-10 18:45 UTC, HAZARD6896 commented
> this is looking good, please style /discord tho lol :3

Done!

2023-06-11 18:40 UTC, Voxalice approved these changes

2023-06-12 20:02 UTC, zedthehedgehog approved these changes

2023-06-15 21:36 UTC, merged